spring:
  application:
    name: record-book
  datasource:
    url: jdbc:postgresql://localhost:5432/recordbook
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  error:
    include-message: always