version: '3.9'
name: RecordBook
services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: recordbook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432